# Generated by Django 4.2.7 on 2025-11-05 15:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('CEREMONY', 'Ceremony'), ('RECEPTION', 'Reception'), ('REHEARSAL', 'Rehearsal Dinner'), ('BRUNCH', 'Day-After Brunch'), ('WELCOME', 'Welcome Party'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('dress_code', models.CharField(blank=True, max_length=100)),
                ('special_instructions', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_time', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='GiftRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registry_type', models.CharField(choices=[('STORE', 'Store Registry'), ('CASH', 'Cash Fund'), ('CHARITY', 'Charity Donation'), ('HONEYMOON', 'Honeymoon Fund')], max_length=20)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Gift Registries',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('plus_one_allowed', models.BooleanField(default=False)),
                ('plus_one_name', models.CharField(blank=True, max_length=200)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('special_notes', models.TextField(blank=True)),
                ('newsletter_subscribed', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content_html', models.TextField(help_text='Rich HTML content')),
                ('content_plain', models.TextField(help_text='Plain text fallback')),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('send_to_all', models.BooleanField(default=False, help_text='Send to all subscribed guests')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(blank=True, related_name='newsletters', to='wedding.guest')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Photo Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('map_url', models.URLField(blank=True, help_text='Google Maps URL')),
                ('website', models.URLField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('table_name', models.CharField(blank=True, help_text="e.g., 'College Friends', 'Family'", max_length=100)),
                ('capacity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='wedding.event')),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='wedding_photos/%Y/%m/')),
                ('caption', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in homepage carousel')),
                ('display_order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='wedding.photocategory')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to='wedding.guest')),
            ],
            options={
                'ordering': ['display_order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='GuestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Moderate before showing publicly')),
                ('is_public', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wedding.guest')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='wedding.venue'),
        ),
        migrations.CreateModel(
            name='SeatingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_assignments', to='wedding.guest')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_assignments', to='wedding.table')),
            ],
            options={
                'unique_together': {('guest', 'table')},
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('YES', 'Attending'), ('NO', 'Not Attending'), ('MAYBE', 'Maybe'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('plus_one_attending', models.BooleanField(default=False)),
                ('meal_choice', models.CharField(blank=True, choices=[('CHICKEN', 'Chicken'), ('BEEF', 'Beef'), ('FISH', 'Fish'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('KIDS', 'Kids Meal')], max_length=20)),
                ('plus_one_meal_choice', models.CharField(blank=True, choices=[('CHICKEN', 'Chicken'), ('BEEF', 'Beef'), ('FISH', 'Fish'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('KIDS', 'Kids Meal')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('song_request', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='wedding.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='wedding.guest')),
            ],
            options={
                'ordering': ['-responded_at'],
                'unique_together': {('guest', 'event')},
            },
        ),
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('bounced', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_logs', to='wedding.guest')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='wedding.newsletter')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('newsletter', 'guest')},
            },
        ),
    ]
